spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/connectdb?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf-8
    # connectdb 부분은 자신의 db 스키마
    username: root
    password: 613111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 기존 db가 서버 실행과 함께 초기화되지 않음 (초기화 : create)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        #    show-sql: true # mysql debug mode, 실제 쿼리가 로그로 보임
        format_sql: true # sql 로그를 포매팅해서 보여줌
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # bind 쿼리의 내용까지 출력. ? 부분이 실제 값으로 표현됨

server:
  port: 8080
